/* NOVA ECE STEAM Lab — metinler. Seslendirilen satırlar: her etkinlikte intro, q (sorular), why; ortak: COMMON_VOICED. */
const AREAS=[
 {id:'sci',host:'piti',img:'piti',acts:['batar','miknatis','golge','buz','fasulye','emme','ses','hava']},
 {id:'eng',host:'zip',img:'zipzip-jump',acts:['kopru','kule','semsiye','rampa','kaldirac']},
 {id:'math',host:'tosbi',img:'tosbi-happy',acts:['ayak','terazi','grafik','simetri','pizza','carpma']},
 {id:'tech',host:'diken',img:'kirpi-happy',acts:['kapi','robot','desen','guvenlik']}];
const ACT_IMG={batar:'apple',miknatis:'makas',golge:'kutuk',buz:'termometre',fasulye:'potFlower',emme:'havlu',ses:'davul',hava:'cloud',
 kopru:'tosbi',kule:'bloklar',semsiye:'semsiye',rampa:'top',kaldirac:'tahterevalli',
 ayak:'kirpi-walk',terazi:'karpuz',grafik:'piti',simetri:'kelebek',pizza:'tepsi-pizza',carpma:'havuc',
 kapi:'kapi',robot:'oyuncak-araba',desen:'palet',guvenlik:'tablet'};
/* STEAM alanı etiketleri (öğretmen paneli için; bir etkinlik birden çok alana katkı yapabilir) */
const STEAM_TAGS={batar:'S',miknatis:'S',golge:'S',buz:'S',fasulye:'S',emme:'S',ses:'SA',hava:'SM',
 kopru:'ET',kule:'EM',semsiye:'ES',rampa:'ESM',kaldirac:'ESM',ayak:'M',terazi:'MS',grafik:'MT',simetri:'MA',pizza:'M',carpma:'MT',
 kapi:'TE',robot:'TE',desen:'AM',guvenlik:'T'};
/* MEB Okul Öncesi Eğitim Programı (2013) bilişsel gelişim kazanım numaraları */
const KAZ={batar:[2,5,7,17],miknatis:[2,5,7,17],golge:[2,5,17,18],buz:[2,5,17,19],fasulye:[2,5,17,18,20],emme:[2,5,7,17],ses:[2,5,8,17],hava:[5,13,18,20],
 kopru:[17,19],kule:[8,9,19],semsiye:[6,17,19],rampa:[2,8,17,19],kaldirac:[2,17,19],ayak:[8,11],terazi:[2,8,9,11],grafik:[4,7,20],simetri:[12,14,15],pizza:[4,15],carpma:[4,16],
 kapi:[13,17,19],robot:[6,17,19],desen:[12,14],guvenlik:[17,19]};
const TX={
tr:{
 ui:{lab:'STEAM Lab',home:'Laboratuvar',start:'Başla',next:'Devam',again:'Yeniden dene',done:'Bitti',back:'Geri',test:'Test et',improve:'Geliştir',check:'Kontrol et',reset:'Baştan',
  predict:'Sence ne olacak?',result:'Sonuç',why:'Neden?',yourGuess:'Tahminin',actual:'Sonuç',right:'Tahminin doğru!',diff:'Sonuç farklı çıktı',score:(a,b)=>`${b} tahminden ${a} tanesi doğru.`,
  tries:n=>`Deneme: ${n}`,budget:'Bütçe',cost:'Maliyet',stars:'Yıldız',listen:'Dinle',areaDone:(a,b)=>`${a} / ${b} etkinlik`,
  teacher:'Öğretmen Paneli',teacherSub:'İlerleme, kazanımlar, ön/son test',storyLink:'Masallardan deneye',storyLinkSub:n=>`${n} masal için “Bu masaldan sonra dene” kartları`,
  areas:{sci:['Bilim Laboratuvarı','Tahmin et, dene, gözle, açıkla.'],eng:['Mühendislik Atölyesi','Tasarla, yap, test et, geliştir.'],math:['Ölç ve Say','Ölç, karşılaştır, say, paylaştır.'],tech:['Teknoloji ve Sanat','Sensör, robot, desen ve güvenli ekran.']},
  home:'Laboratuvar',youCan:'Evde dene',safe:'Güvenlik',mat:'Malzemeler'},
 c:{app:'NOVA ECE STEAM Lab’a hoş geldin! Bir laboratuvar seç. Bilim, mühendislik, matematik, teknoloji ve sanat seni bekliyor.',
  dogru:'Tahminin doğru çıktı!',farkli:'Sonuç tahmininden farklı çıktı. Sorun değil, bilim insanları da böyle öğrenir!',
  test:'Haydi, test edelim!',basari:'Harika! Tasarımın işe yaradı!',gelistir:'Hımm, olmadı. Nasıl daha iyi olur? Bir şeyi değiştirip yeniden dene.',
  bravo:'Aferin! Bu etkinliği bitirdin.',yanlis:'Bir daha bak, sen yaparsın!',sec:'Önce bir seçim yap.'},
 a:{
 batar:{t:'Batar mı, Yüzer mi?',d:'Altı eşyayı suya bırak, önce tahmin et.',intro:'Su dolu kabımıza eşyaları tek tek bırakacağız. Önce tahmin et: batar mı, yüzer mi?',
  opts:['Batar','Yüzer'],items:{apple:'Elma',tas:'Taş',yaprak:'Yaprak','bozuk-para':'Bozuk para',top:'Top',kasik:'Metal kaşık'},
  res:['battı','yüzdü'],why:'Taş, para ve metal kaşık suyun dibine battı. Elma, top ve yaprak suyun üstünde kaldı. Batıp batmamak yalnız büyüklüğe bağlı değildir. İçinde hava olan ve boyuna göre hafif olan şeyler yüzer.',
  home:'Bir leğene su doldurun. Evdeki güvenli eşyaları önce “batar” ve “yüzer” diye iki gruba ayırın, sonra deneyin.'},
 miknatis:{t:'Mıknatıs Neyi Çeker?',d:'Mıknatısı eşyalara yaklaştır.',intro:'Bu bir mıknatıs. Eşyalara yaklaştıracağız. Sence mıknatıs onu çeker mi, çekmez mi?',
  opts:['Çeker','Çekmez'],items:{atac:'Ataç',kasik:'Metal kaşık',yaprak:'Yaprak',makas:'Makas',kagit:'Kâğıt','oyuncak-ayi':'Pelüş ayı'},
  res:['çekti','çekmedi'],why:'Mıknatıs demir ve çelikten yapılmış eşyaları çeker. Ataç, metal kaşık ve makasın metal kısmı çelikten yapılmıştır. Kâğıt, yaprak ve pelüş ayı demir değildir, bu yüzden çekilmezler.',
  home:'Buzdolabı mıknatısıyla evde dolaşın: kapı kolu, kaşık, tahta kaşık, kalem… Hangileri yapıştı? Bir listeye çizin.'},
 golge:{t:'Gölgem Nerede?',d:'Güneş hareket edince gölge nasıl değişir?',intro:'Güneş sabah doğar, öğlen tepeye çıkar, akşam batar. Kütüğün gölgesine ne olacak? Tahmin edelim.',
  q:['Sabah güneş alçakta. Gölge uzun mu, kısa mı olur?','Öğlen güneş tepede. Gölge uzun mu, kısa mı olur?','Akşam güneş yine alçakta. Gölge uzun mu, kısa mı olur?'],
  opts:['Uzun','Kısa'],times:['Sabah','Öğle','Akşam'],why:'Güneş gökyüzünde alçaktayken gölgeler uzun olur. Öğle vakti güneş tepemizdeyken gölgeler kısalır. Gölge her zaman güneşin karşı tarafına düşer.',
  free:'Güneşi sürükle, gölgeyi izle.',home:'Güneşli bir günde sabah, öğle ve akşam aynı yerde durup gölgenizin ucunu tebeşirle işaretleyin.'},
 buz:{t:'Buz Nerede Erir?',d:'Güneşte, gölgede ve buzdolabında üç buz.',intro:'Üç buz küpümüz var. Birini güneşe, birini gölgeye, birini buzdolabına koyduk.',
  q:['Sence hangi buz en hızlı erir?','Peki hangisi en yavaş erir?'],opts:['Güneşte','Gölgede','Buzdolabında'],
  why:'Güneşteki buz en hızlı eridi çünkü orası en sıcaktı. Buzdolabının içi soğuk olduğu için oradaki buz neredeyse hiç erimedi. Sıcaklık arttıkça buz daha hızlı erir.',
  home:'Üç tabağa birer buz koyun: güneşli pencere önü, gölge bir köşe, buzdolabı. Her 10 dakikada bir bakıp resmini çizin.'},
 fasulye:{t:'Fasulye Günlüğü',d:'7 günde iki saksıyı gözle; kendi günlüğünü tut.',intro:'İki saksıya birer fasulye ektik. Birini her gün sulayacağız, ötekini hiç sulamayacağız.',
  q:['Sence hangi saksıdaki fasulye büyür?'],opts:['Sulanan saksı','Sulanmayan saksı','İkisi de'],pots:['Sulanan','Sulanmayan'],
  day:n=>`${n}. gün`,water:'Sula',nextDay:'Gün geçsin',cm:'cm',needWater:'Önce sulanan saksıyı sula!',
  why:'Bitkilerin büyümek için suya, ışığa ve havaya ihtiyacı vardır. Su almayan fasulye filizlenemedi. Sulanan fasulye önce kök, sonra gövde ve yaprak çıkardı.',
  diary:'Gerçek günlüğüm',diaryHelp:'Evde bir fasulyeyi ıslak pamukta çimlendirin. Her gün bir resim seçin ve boyunu ölçün.',stages:['Tohum','Kök','Filiz','İki yaprak','Dört yaprak','Uzun fide'],
  home:'Bir kavanoza ıslak pamuk ve fasulye koyun. 7 gün boyunca her gün aynı saatte bakıp günlüğe işleyin.'},
 emme:{t:'Hangisi Suyu Emer?',d:'Malzemelere su damlat, emer mi emmez mi?',intro:'Malzemelerin üstüne su damlatacağız. Sence su içine çekilir mi, yoksa üstünde mi kalır?',
  opts:['Emer','Emmez'],items:{havlu:'Havlu',poset:'Plastik poşet',kagit:'Kâğıt havlu',yaprak:'Yaprak',atki:'Yün atkı',eldiven:'Yün eldiven'},res:['emdi','emmedi'],
  why:'Havlu, kâğıt havlu ve yün gibi malzemelerin içinde minicik boşluklar vardır. Su bu boşluklara dolar, yani emilir. Poşet ve yaprağın yüzeyi suyu içeri almaz; su üstünde damla olarak kalır.',
  home:'Bir damlalıkla kâğıt havlu, poşet, pamuklu kumaş ve alüminyum folyonun üstüne su damlatın. Hangisi emdi?'},
 ses:{t:'Ses Titreşimi',d:'Davul, pirinç taneleri ve lastikler.',intro:'Ses nasıl oluşur? Davulun üstüne pirinç taneleri koyduk. Haydi deneyelim!',
  q:['Davula vurunca pirinç taneleri ne yapar?','Hafif mi vurursak, güçlü mü vurursak pirinçler daha yükseğe zıplar?','İnce lastik mi, kalın lastik mi daha ince ses çıkarır?'],
  opts:[['Zıplar','Kıpırdamaz'],['Hafif','Güçlü'],['İnce lastik','Kalın lastik']],hit:['Hafif vur','Güçlü vur'],pluck:'Lastiğe dokun',thin:'İnce',thick:'Kalın',
  why:'Ses bir titreşimdir. Davula vurunca deri titrer, pirinçler de zıplar. Güçlü vurunca titreşim büyür ve ses yükselir. İnce lastik daha hızlı titrer, bu yüzden daha ince ses çıkarır.',
  home:'Bir kâsenin ağzına streç film gerin, üstüne birkaç pirinç koyun. Yanında tencere kapağına vurun ya da yüksek sesle “aaa” deyin.'},
 hava:{t:'Hava Durumu Günlüğü',d:'Her gün gökyüzüne bak, kaydet, grafiğe dök.',intro:'Her gün gökyüzüne bak ve bugünün havasını kaydet. Yarın için de bir tahmin yap!',
  kinds:['Güneşli','Bulutlu','Yağmurlu','Karlı','Rüzgârlı'],feel:['Sıcak','Ilık','Soğuk'],today:'Bugün hava nasıl?',tomorrow:'Yarın nasıl olacak? Tahmin et.',saved:'Kaydedildi! Yarın tahminine bakacağız.',
  yest:(p,a)=>`Dün tahminin: ${p}. Bugün: ${a}.`,count:'Günlüğümün grafiği',days:'gün',q:['Bugün hava nasıl?'],
  why:'Havayı her gün aynı saatte gözlemleyip kaydetmek bilim insanlarının yaptığı iştir. Kayıtlar biriktikçe hangi havanın daha sık olduğunu grafikte görebiliriz.',
  home:'Takvime her gün bir hava resmi çizin. Hafta sonunda resimleri sayıp sütun grafiği yapın.'},
 kopru:{t:'Tosbi’ye Köprü',why:'Mühendisler önce tasarlar, sonra test eder. Kemer ve üçgen şekiller yükü yanlara dağıttığı için köprüyü güçlendirir. Ortadaki bir destek ayağı da köprünün esnemesini azaltır.',d:'Malzeme, şekil ve destek seç; bütçeyi aşma.',intro:'Tosbi dereyi geçmek istiyor! Bir köprü tasarla. Ama dikkat: bütçen 6 jeton.',
  g:{mat:'Malzeme',shape:'Şekil',leg:'Destek ayağı'},mat:['Kâğıt','Karton','Tahta'],shape:['Düz','Kemer','Üçgen kafes'],leg:['Yok','Ortada bir ayak'],
  h:{weak:'Köprü çok esnedi ve kırıldı. Daha sağlam bir şekil ya da bir destek ayağı dene.',budget:'Bu tasarım bütçeyi aşıyor. Daha ucuz bir malzeme ya da şekil seç.',ok:'Tosbi karşıya geçti!'},
  home:'İki kitap yığını arasına bir kâğıt koyun, üstüne bozuk para dizin. Kâğıdı katlayarak (akordiyon) yeniden deneyin.'},
 kule:{t:'En Yüksek Kule',why:'Sağlam bir kulenin tabanı geniştir. Ağır ve geniş bloklar alta, hafif ve küçük bloklar üste gelince kule dengede kalır.',d:'Blokları diz; devrilmesin, rüzgâra dayansın.',intro:'Blokları üst üste dizerek beş katlı bir kule yap. Devrilmesin!',
  blocks:['Büyük','Orta','Küçük','Çatı'],r:['5 katlı kule','Rüzgâr testi: 6 katlı kule'],undo:'Geri al',wind:'Rüzgâr',
  h:{wide:'Geniş bir blok dar bir bloğun üstünde durmaz. Genişleri alta koy.',roof:'Çatının üstüne blok konmaz. Çatıyı en üste koy.',short:'Kule henüz yeterince yüksek değil.',windy:'Rüzgâr kuleyi salladı! En alta en geniş bloğu koy.',ok:'Kule dimdik ayakta!'},
  home:'Bardak, kitap ya da kutularla kule yapın. Bir yelpazeyle rüzgâr testi yapın; tabanı genişletince ne oluyor?'},
 semsiye:{t:'Diken’e Şemsiye',why:'İyi bir şemsiye su geçirmeyen bir örtüye ve sağlam bir sapa ihtiyaç duyar. Kubbe şekli suyu kenarlara akıtır. Mühendisler malzemeyi işe göre seçer.',d:'Örtü, sap ve şekil seç; yağmur testi yap.',intro:'Yağmur geliyor! Diken için bir şemsiye tasarla. Örtüsü, sapı ve şekli senden.',
  g:{cover:'Örtü',stick:'Sap',shape:'Şekil'},cover:['Kâğıt','Plastik','Kumaş'],stick:['Pipet','Tahta çubuk'],shape:['Düz','Kubbe'],
  h:{paper:'Kâğıt ıslanınca yumuşadı ve yırtıldı. Su geçirmeyen bir örtü dene.',cloth:'Kumaştan su yavaş yavaş damladı. Daha iyi bir örtü dene.',straw:'Pipet sap rüzgârda büküldü. Daha sağlam bir sap seç.',flat:'Diken kuru kaldı ama düz örtüde su birikti. Kubbe şekli suyu kenara akıtır.',ok:'Diken kupkuru!'},
  home:'Bir oyuncağı yağmurdan korumak için kâğıt, poşet ve kumaştan küçük şemsiyeler yapın; üstüne bardakla su dökün.'},
 rampa:{t:'Rampadan Top',why:'Rampa yükseldikçe top daha hızlı iner ve daha uzağa gider. Kaygan yüzeyler topu az yavaşlatır, pütürlü halı ise çok yavaşlatır. Her seferinde tek bir şeyi değiştirince nedenini anlarız.',d:'Yüksekliği ve yüzeyi değiştir, topu sepete ulaştır.',intro:'Topu rampadan bırakacağız. Topun sepette durması için rampanın yüksekliğini ve yüzeyini seç.',
  g:{h:'Yükseklik',s:'Yüzey'},hs:['1 kutu','2 kutu','3 kutu'],ss:['Halı','Tahta','Buz'],round:n=>`Tur ${n}`,
  h:{short:'Top sepete varmadan durdu. Rampayı yükselt ya da daha kaygan bir yüzey seç.',long:'Top sepeti geçti. Rampayı alçalt ya da daha pütürlü bir yüzey seç.',ok:'Top tam sepette!'},
  home:'Bir kitabı ya da tepsiyi rampa yapın. Altına 1, 2, 3 kitap koyup oyuncak arabayı bırakın; nerede durduğunu bantla işaretleyin.'},
 kaldirac:{t:'Kaldıraçla Taşı Kaldır',why:'Kaldıraç ağır yükleri az güçle kaldırmamızı sağlar. Destek noktası yüke ne kadar yakın olursa, öbür uçtan bastırmak o kadar kolaylaşır.',d:'Destek noktasını kaydır, taşı havaya kaldır.',intro:'Zıpzıp kocaman bir taşı kaldırmak istiyor. Bir tahta ve bir destek noktasıyla kaldıraç yapacağız.',
  q:['Destek noktasını kaydır. Taşı kaldırabilecek misin?','Bu taş daha ağır! Destek noktası nereye gelmeli?','Destek noktası sabit. Taşı kaldırmak için kaç tavşan bastırmalı?'],
  fulcrum:'Destek noktası',push:'Bastır',bunnies:'Tavşan sayısı',
  h:{fail:'Taş kalkmadı. Destek noktasını taşa yaklaştır ya da daha çok güç kullan.',ok:'Taş havada!'},
  home:'Bir cetveli kalemin üstüne koyun. Bir ucuna silgi koyup öbür ucuna parmağınızla bastırın. Kalemi silgiye yaklaştırınca ne değişiyor?'},
 ayak:{t:'Kaç Ayak?',d:'Kütüğü ayaklarla ölç, sonuçları karşılaştır.',intro:'Bu kütük ne kadar uzun? Cetvelimiz yok ama ayaklarımız var! Haydi ölçelim.',
  q:['Diken’in ayaklarıyla ölç. Kütük kaç ayak uzunluğunda?','Şimdi Zıpzıp’ın büyük ayaklarıyla ölç. Kaç ayak?','Neden farklı sayılar bulduk?','Herkes aynı sonucu bulsun diye aynı büyüklükte bloklarla ölçelim. Kaç blok?'],
  place:'Ayak koy',placeB:'Blok koy',why2:['Ayaklarımızın boyu farklı','Kütük küçüldü'],
  why:'Diken’in ayakları küçük olduğu için daha çok ayak saydık. Zıpzıp’ın ayakları büyük olduğu için daha az saydık. Herkesin aynı sonucu bulması için aynı birimi kullanırız; cetvel de bu yüzden vardır.',
  home:'Masayı, halıyı ya da kanepeyi önce sizin, sonra çocuğun adımlarıyla ölçün. Sonuçları karşılaştırın.'},
 terazi:{t:'Kim Daha Ağır?',d:'Terazide karşılaştır; büyük her zaman ağır mı?',intro:'Teraziye iki şey koyacağız. Ağır olan taraf aşağı iner. Önce tahmin et!',
  q:['Hangisi daha ağır?','Hangisi daha ağır?','Hangisi daha ağır?','En ağırı hangisi?'],
  items:{karpuz:'Karpuz',uzum:'Üzüm','oyuncak-ayi':'Pelüş ayı',tas:'Taş',kitap:'Kitap',apple:'Elma'},
  why:'Terazide ağır olan taraf aşağı iner. Pelüş ayı taştan büyük ama daha hafif! Büyük olan her zaman ağır olmaz; ağırlığı ölçmek için tartarız.',
  home:'Bir askıya iki poşet asarak terazi yapın. Oyuncakları ikişer ikişer karşılaştırıp en hafiften en ağıra dizin.'},
 grafik:{t:'Pıtı’nın Grafiği',d:'Hava gözlemlerini say, sütun grafiği yap.',intro:'Pıtı on gün boyunca havayı gözledi. Her havadan kaç gün olduğunu sayıp grafiğe dökelim.',
  q:['Her sütunu doğru yüksekliğe getir.','En çok hangi hava oldu?','Yağmurlu günler mi daha çok, bulutlu günler mi?'],own:'Kendi günlüğümün grafiği',
  why:'Grafik, saydıklarımızı bir bakışta görmemizi sağlar. En uzun sütun en çok olan havayı gösterir.',
  home:'Bir hafta boyunca kahvaltıda kimin hangi meyveyi yediğini sayın; kâğıda yapışkan notlarla sütun grafiği yapın.'},
 simetri:{t:'Kelebeğin Öbür Kanadı',d:'Aynadaki gibi boya: simetri.',intro:'Kelebeğin bir kanadı boyalı. Öbür kanadı ayna gibi aynısı olacak şekilde boya!',
  q:['Öbür kanadı ayna gibi boya.'],round:n=>`Kelebek ${n}`,
  why:'Simetride bir çizginin iki yanı ayna gibi aynıdır. Kelebeklerin, yaprakların ve yüzümüzün iki yanı neredeyse simetriktir.',
  home:'Bir kâğıdı ortadan katlayın, bir yarısına boya damlatıp kapatın. Açınca simetrik bir kelebek çıkar!'},
 pizza:{t:'Pizzayı Paylaştır',d:'Eşit dilimler: yarım, çeyrek, üçte bir.',intro:'Arkadaşlar pizza yiyecek. Herkes eşit pay almalı. Pizzayı kaç dilime keselim?',
  q:['İki arkadaş var. Pizzayı kaç dilime kesersen herkes eşit alır?','Dört arkadaş var. Kaç dilim?','Üç arkadaş var. Kaç dilim?'],cut:'Dilim sayısı',share:'Paylaştır',
  frac:['yarım (1/2)','çeyrek (1/4)','üçte bir (1/3)'],each:f=>`Her biri pizzanın ${f} kadarını aldı.`,unfair:'Paylar eşit olmadı! Bir dilim arttı ya da birinin payı az kaldı.',
  why:'Bir bütünü eşit parçalara ayırınca her parçaya bir ad veririz: ikiye bölünce yarım, dörde bölünce çeyrek, üçe bölünce üçte bir.',
  home:'Bir ekmeği, elmayı ya da kâğıttan bir pizzayı aile üyeleri arasında eşit paylaştırın. Her parçaya bir ad verin.'},
 carpma:{t:'Sepet Sepet Havuç',d:'Tekrarla bloğuyla çarpma.',intro:'Code’daki tekrarla bloğunu hatırlıyor musun? Onunla sepetlere havuç koyacağız!',
  q:['3 sepete 4’er havuç koy. Toplam kaç havuç olur?','2 sepete 5’er havuç koy. Toplam kaç?','12 havucu 4’er 4’er koyarsak kaç sepet gerekir?'],
  baskets:'Sepet (tekrarla)',per:'Her sepete',run:'Çalıştır',total:'Toplam kaç havuç?',howMany:'Kaç sepet?',
  why:'Aynı sayıyı tekrar tekrar eklemek çarpmadır: 4 + 4 + 4 = 3 kere 4 = 12. Tekrarla bloğu da aynı işi tekrar tekrar yapar.',
  home:'Yumurta kolisi ya da kaplarla “3 kapta 2’şer düğme” gibi gruplar yapın; önce sayın, sonra kısa yolunu bulun.'},
 kapi:{t:'Kendi Kendine Açılan Kapı',d:'Sensör + eğer: akıllı aletler.',intro:'Market kapısı kendi kendine nasıl açılır? Bir sensör ve bir eğer kuralıyla! Kuralı sen kur.',
  sc:['Market kapısı','Gece lambası','Akıllı saksı'],if:'EĞER',then:'O ZAMAN',sens:['biri yaklaşırsa','hava kararırsa','toprak kuruysa','ses olursa'],acts:['kapı açılsın','lamba yansın','su verilsin','müzik çalsın'],
  q:['Market kapısı için kuralı kur.','Gece lambası için kuralı kur.','Akıllı saksı için kuralı kur.'],
  h:{bad:'Bu kural bu alete uymadı. Sensörü ya da işi değiştir.',ok:'Kural çalıştı!'},
  why:'Sensörler çevredeki değişikliği fark eder: hareket, ışık, nem, ses. Program da “eğer bu olursa, şunu yap” der. Otomatik kapılar, gece lambaları ve akıllı saksılar böyle çalışır.',
  home:'Evde sensörle çalışan aletleri arayın: otomatik kapı, hareketle yanan ışık, musluk… Her biri için “eğer… o zaman…” cümlesi kurun.'},
 robot:{t:'Robot Kol Tasarla',d:'Tutucu ve eklem seç, görevleri yap.',intro:'Bir robot kol tasarlayacağız. Her görev için doğru tutucuyu ve yeterli eklemi seç.',
  g:{grip:'Tutucu',joint:'Eklem sayısı'},grip:['Kıskaç','Mıknatıs','Kepçe'],joint:['1','2','3'],
  q:['Masadaki topu al.','Dağılmış ataçları topla.','Kumu kovaya taşı.','Yüksek raftaki ayıyı al.'],
  h:{grip:'Bu tutucu bu işe uymadı. Başka bir tutucu dene.',reach:'Kol yetişemedi. Daha çok eklem ekle.',ok:'Robot kol görevi yaptı!'},
  why:'Mühendisler bir robotu yapacağı işe göre tasarlar. Kıskaç tutar, mıknatıs metal parçaları toplar, kepçe kum ve su taşır. Eklemler kolun uzanmasını ve bükülmesini sağlar.',
  dough:'Oyun hamuru ile yap',doughText:'Oyun hamuru, pipet ve dondurma çubuklarıyla eklemli bir kol yapın. Hamur topları eklem olsun; uca iki çubukla bir kıskaç ekleyin.',
  home:'Oyun hamuru, pipet ve dondurma çubuklarıyla bir robot kol yapın. Hangi uç ponpon toplamakta daha iyi?'},
 desen:{t:'Simetrik Desen Atölyesi',d:'Ayna çizgileriyle kaleydoskop çizimi.',intro:'Burada çizdiğin her çizgi aynalarda tekrar eder. Ayna sayısını seç ve çizmeye başla!',
  mirrors:'Ayna sayısı',clear:'Temizle',size:'Kalınlık',q:['Ayna sayısını seç ve çiz.'],
  why:'Ayna çizgisinin iki yanındaki şekiller birbirinin aynısıdır. Kilimlerde, çinilerde ve kar tanelerinde bu desenleri görürüz.',
  home:'Bir kâğıdı dörde katlayıp köşelerinden kesin; açınca simetrik bir kar tanesi çıkar.'},
 guvenlik:{t:'Ekranda Kiminle Konuşabilirim?',d:'Pıtı’nın dijital güvenlik masalı.',intro:'Pıtı’nın tablet macerasını dinle. Bazı yerlerde Pıtı’ya sen yardım edeceksin.',
  pages:['Pıtı tablette en sevdiği oyunu oynuyordu.','Birden bir mesaj geldi: “Merhaba! Adın ne, nerede oturuyorsun?” Pıtı bu kişiyi tanımıyordu.','Annesi mesajı okudu: “Bana gösterdiğin için teşekkür ederim. Tanımadığımız kişilere adımızı, adresimizi ve fotoğrafımızı vermeyiz.”','Sonra oyunda parlak bir düğme belirdi: “Bedava altın için hemen tıkla!”','Pıtı uzun süredir oynuyordu. Gözleri yoruldu, başı ağrımaya başladı.','Pıtı kuralları bir kartta topladı: Tanımadığına bilgi verme. Emin değilsen bir büyüğe sor. Ekrana mola ver. İnternette de nazik ol.'],
  choice:{1:['Adresimi yazarım.','Yazmam, bir büyüğüme gösteririm.'],3:['Hemen tıklarım.','Önce bir büyüğe sorarım.'],4:['Bir saat daha oynarım.','Tableti kapatıp dışarıda oynarım.']},
  good:'Çok doğru bir seçim!',bad:'Hımm, bu güvenli değil. Bir daha düşünelim.',why:'Ekranda da gerçek hayattaki gibi kurallar vardır. Tanımadığımız kişilere bilgi vermeyiz, emin olmadığımızda bir büyüğe sorarız ve ekrana mola veririz.',
  home:'Ailece bir “ekran kuralları” kartı hazırlayın ve tabletin yanına asın.'}
 },
 teacher:{title:'Öğretmen Paneli',prog:'STEAM alanlarında ilerleme',acts:'etkinlik',kaz:'Kazanım eşlemesi',kazNote:'Numaralar MEB Okul Öncesi Eğitim Programı (2013) bilişsel gelişim kazanımlarıdır. 2024 Türkiye Yüzyılı Maarif Modeli ile güncel eşlemenin öğretmen tarafından kontrol edilmesi önerilir.',
  kazNames:{2:'Tahminde bulunur',4:'Nesneleri sayar',5:'Gözlem yapar',6:'Özelliklerine göre eşleştirir',7:'Gruplar',8:'Özelliklerini karşılaştırır',9:'Sıralar',11:'Ölçer',12:'Geometrik şekilleri tanır',13:'Sembolleri tanır',14:'Örüntü oluşturur',15:'Parça-bütün ilişkisini kavrar',16:'Basit toplama/çıkarma yapar',17:'Neden-sonuç ilişkisi kurar',18:'Zamanla ilgili kavramları açıklar',19:'Problem durumlarına çözüm önerir',20:'Nesne grafiği hazırlar'},
  col:['Etkinlik','Alan','Kazanımlar','Durum'],done:'Tamam',notyet:'—',
  pre:'Ön test / son test (pilot)',preNote:'Bu kısa form çocuğun STEAM’e ilgisini resimli yüzlerle tarar. Geçerlik ve güvenirlik çalışması yapılmamıştır; pilot amaçlıdır. Veriler yalnız bu cihazda saklanır, ad yerine kod kullanın.',
  code:'Çocuk kodu',phase:'Aşama',phases:['Ön test','Son test'],begin:'Formu başlat',answers:['Hayır','Biraz','Evet'],finish:'Kaydedildi.',
  items:['Yeni şeyler denemeyi severim.','Bir şeyin nasıl çalıştığını merak ederim.','Deney yapmak eğlencelidir.','Bir şey olmayınca yeniden denerim.','Saymayı ve ölçmeyi severim.','Bir şeyler inşa etmeyi severim.','Doğadaki canlıları gözlemlemeyi severim.','Resim ve desen yapmayı severim.','Büyüyünce bilim insanı ya da mühendis olabilirim.','Merak ettiğim şeyleri sorarım.'],
  records:'Kayıtlar',none:'Henüz kayıt yok.',copy:'CSV olarak kopyala',copied:'Kopyalandı.',copyFail:'Kopyalanamadı; metni seçip kopyalayın.',total:'Toplam',
  design:'Önerilen pilot desen',designText:'Tek grup ön test–son test: (1) Ön test, (2) 4 hafta boyunca haftada 3 STEAM Lab etkinliği ve eşlik eden fişsiz etkinlik, (3) Son test. Küçük örneklemde ön ve son puanlar Wilcoxon işaretli sıralar testiyle karşılaştırılabilir; etkinlik kullanım kayıtları uygulama sadakati için raporlanabilir.',
  usage:'Kullanım kaydı',reset:'Tüm verileri sil',resetq:'Emin misin? Bir kez daha dokun.',resetok:'Silindi.',del:'Sil'},
 story:{title:'Masallardan Deneye',sub:'NOVA ECE Kids masallarından sonra yapılacak deney kartları.',open:'Etkinliği aç',home:'Evde dene'}
},
en:{
 ui:{lab:'STEAM Lab',home:'Lab',start:'Start',next:'Next',again:'Try again',done:'Done',back:'Back',test:'Test it',improve:'Improve',check:'Check',reset:'Reset',
  predict:'What do you think will happen?',result:'Result',why:'Why?',yourGuess:'Your guess',actual:'Result',right:'You guessed right!',diff:'The result was different',score:(a,b)=>`${a} of ${b} guesses were right.`,
  tries:n=>`Tries: ${n}`,budget:'Budget',cost:'Cost',stars:'Stars',listen:'Listen',areaDone:(a,b)=>`${a} / ${b} activities`,
  teacher:'Teacher Panel',teacherSub:'Progress, learning goals, pre/post test',storyLink:'From stories to experiments',storyLinkSub:n=>`“Try this after the story” cards for ${n} stories`,
  areas:{sci:['Science Lab','Predict, test, observe, explain.'],eng:['Engineering Workshop','Design, build, test, improve.'],math:['Measure and Count','Measure, compare, count, share.'],tech:['Technology and Art','Sensors, robots, patterns and safe screens.']},
  home:'Lab',youCan:'Try at home',safe:'Safety',mat:'Materials'},
 c:{app:'Welcome to the NOVA ECE STEAM Lab! Choose a lab. Science, engineering, maths, technology and art are waiting for you.',
  dogru:'Your guess was right!',farkli:'The result was different from your guess. That is fine, scientists learn this way too!',
  test:'Let us test it!',basari:'Great! Your design worked!',gelistir:'Hmm, that did not work. How can we make it better? Change one thing and try again.',
  bravo:'Well done! You finished this activity.',yanlis:'Look again, you can do it!',sec:'Make a choice first.'},
 a:{
 batar:{t:'Sink or Float?',d:'Drop six things in water, guess first.',intro:'We will drop things into our tub of water one by one. Guess first: will it sink or float?',
  opts:['Sink','Float'],items:{apple:'Apple',tas:'Stone',yaprak:'Leaf','bozuk-para':'Coin',top:'Ball',kasik:'Metal spoon'},
  res:['sank','floated'],why:'The stone, the coin and the metal spoon sank to the bottom. The apple, the ball and the leaf stayed on top. Sinking is not only about size. Things that have air inside and are light for their size float.',
  home:'Fill a bowl with water. First sort some safe objects into “sink” and “float” groups, then test them.'},
 miknatis:{t:'What Does a Magnet Pull?',d:'Bring the magnet close to things.',intro:'This is a magnet. We will bring it close to some things. Do you think the magnet will pull it or not?',
  opts:['Pulls','Does not pull'],items:{atac:'Paper clip',kasik:'Metal spoon',yaprak:'Leaf',makas:'Scissors',kagit:'Paper','oyuncak-ayi':'Teddy bear'},
  res:['pulled','did not pull'],why:'A magnet pulls things made of iron and steel. The paper clip, the metal spoon and the metal part of the scissors are made of steel. Paper, leaves and teddy bears are not iron, so they are not pulled.',
  home:'Walk around the house with a fridge magnet: door handle, spoon, wooden spoon, pencil… Which ones stuck? Draw a list.'},
 golge:{t:'Where Is My Shadow?',d:'How does a shadow change as the sun moves?',intro:'The sun rises in the morning, climbs high at noon and sets in the evening. What will happen to the log’s shadow? Let us guess.',
  q:['In the morning the sun is low. Will the shadow be long or short?','At noon the sun is high. Will the shadow be long or short?','In the evening the sun is low again. Will the shadow be long or short?'],
  opts:['Long','Short'],times:['Morning','Noon','Evening'],why:'When the sun is low in the sky, shadows are long. At noon, when the sun is high above us, shadows get short. A shadow always falls on the side away from the sun.',
  free:'Drag the sun and watch the shadow.',home:'On a sunny day, stand in the same spot in the morning, at noon and in the evening, and mark the end of your shadow with chalk.'},
 buz:{t:'Where Does Ice Melt?',d:'Three ice cubes: sun, shade and fridge.',intro:'We have three ice cubes. We put one in the sun, one in the shade and one in the fridge.',
  q:['Which ice cube do you think will melt fastest?','And which one will melt slowest?'],opts:['In the sun','In the shade','In the fridge'],
  why:'The ice in the sun melted fastest because it was the warmest place. The fridge is cold inside, so that ice hardly melted at all. The warmer it is, the faster ice melts.',
  home:'Put an ice cube on three plates: a sunny window, a shady corner and the fridge. Look every 10 minutes and draw what you see.'},
 fasulye:{t:'Bean Diary',d:'Watch two pots for 7 days; keep your own diary.',intro:'We planted a bean in each of two pots. We will water one every day and never water the other.',
  q:['Which pot do you think will grow a plant?'],opts:['The watered pot','The dry pot','Both'],pots:['Watered','Not watered'],
  day:n=>`Day ${n}`,water:'Water',nextDay:'Next day',cm:'cm',needWater:'Water the watered pot first!',
  why:'Plants need water, light and air to grow. The bean without water could not sprout. The watered bean grew a root first, then a stem and leaves.',
  diary:'My real diary',diaryHelp:'Sprout a bean on wet cotton at home. Each day, choose a picture and measure its height.',stages:['Seed','Root','Sprout','Two leaves','Four leaves','Tall seedling'],
  home:'Put wet cotton and a bean in a jar. Check it at the same time every day for 7 days and record it in the diary.'},
 emme:{t:'Which One Soaks Up Water?',d:'Drip water on materials: does it soak in?',intro:'We will drip water onto some materials. Will the water soak in, or stay on top?',
  opts:['Soaks up','Does not'],items:{havlu:'Towel',poset:'Plastic bag',kagit:'Paper towel',yaprak:'Leaf',atki:'Wool scarf',eldiven:'Wool mittens'},res:['soaked it up','did not soak it up'],
  why:'Towels, paper towels and wool have tiny spaces inside. Water fills these spaces, so it soaks in. A plastic bag and a leaf do not let water in; it stays on top as a drop.',
  home:'Use a dropper to drip water on a paper towel, a plastic bag, cotton cloth and kitchen foil. Which ones soaked it up?'},
 ses:{t:'Sound Vibrations',d:'A drum, grains of rice and rubber bands.',intro:'How is sound made? We put some grains of rice on a drum. Let us try!',
  q:['When we hit the drum, what will the rice do?','Will the rice jump higher if we tap softly or hit hard?','Which makes a higher sound, a thin rubber band or a thick one?'],
  opts:[['Jump','Stay still'],['Softly','Hard'],['Thin band','Thick band']],hit:['Tap softly','Hit hard'],pluck:'Pluck a band',thin:'Thin',thick:'Thick',
  why:'Sound is a vibration. When we hit the drum, the skin vibrates and the rice jumps. A hard hit makes a bigger vibration and a louder sound. A thin band vibrates faster, so it makes a higher sound.',
  home:'Stretch cling film over a bowl and put a few grains of rice on top. Bang a pan lid next to it, or sing a loud “aaah”.'},
 hava:{t:'Weather Diary',d:'Look at the sky every day, record it, make a graph.',intro:'Look at the sky every day and record today’s weather. Make a guess for tomorrow too!',
  kinds:['Sunny','Cloudy','Rainy','Snowy','Windy'],feel:['Hot','Warm','Cold'],today:'What is the weather like today?',tomorrow:'What will it be like tomorrow? Make a guess.',saved:'Saved! We will check your guess tomorrow.',
  yest:(p,a)=>`Yesterday you guessed: ${p}. Today: ${a}.`,count:'My diary graph',days:'days',q:['What is the weather like today?'],
  why:'Watching and recording the weather at the same time every day is what scientists do. As the records add up, a graph shows which weather happens most often.',
  home:'Draw a weather picture on a calendar every day. At the end of the week, count the pictures and make a bar graph.'},
 kopru:{t:'A Bridge for Tosbi',why:'Engineers design first, then test. Arches and triangles spread the load to the sides, so they make a bridge stronger. A support leg in the middle also stops the bridge bending.',d:'Choose material, shape and support; stay on budget.',intro:'Tosbi wants to cross the stream! Design a bridge. But careful: your budget is 6 coins.',
  g:{mat:'Material',shape:'Shape',leg:'Support leg'},mat:['Paper','Cardboard','Wood'],shape:['Flat','Arch','Triangle truss'],leg:['None','One leg in the middle'],
  h:{weak:'The bridge bent too much and broke. Try a stronger shape or a support leg.',budget:'This design is over budget. Choose a cheaper material or shape.',ok:'Tosbi got across!'},
  home:'Lay a sheet of paper between two piles of books and line up coins on it. Fold the paper like a fan and try again.'},
 kule:{t:'The Tallest Tower',why:'A strong tower has a wide base. When the heavy, wide blocks are at the bottom and the light, small blocks are on top, the tower stays balanced.',d:'Stack the blocks so they do not fall, even in wind.',intro:'Stack the blocks to build a tower five blocks high. Do not let it fall!',
  blocks:['Big','Medium','Small','Roof'],r:['5-block tower','Wind test: 6-block tower'],undo:'Undo',wind:'Wind',
  h:{wide:'A wide block will not stay on top of a narrow one. Put the wide ones at the bottom.',roof:'You cannot put a block on the roof. Put the roof on top.',short:'The tower is not tall enough yet.',windy:'The wind shook the tower! Put the widest block at the bottom.',ok:'The tower is standing tall!'},
  home:'Build towers with cups, books or boxes. Do a wind test with a fan; what happens when you make the base wider?'},
 semsiye:{t:'An Umbrella for Spike',why:'A good umbrella needs a waterproof cover and a strong handle. A dome shape makes water run off the edges. Engineers choose materials that suit the job.',d:'Choose cover, handle and shape; do a rain test.',intro:'Rain is coming! Design an umbrella for Spike. You choose the cover, the handle and the shape.',
  g:{cover:'Cover',stick:'Handle',shape:'Shape'},cover:['Paper','Plastic','Cloth'],stick:['Straw','Wooden stick'],shape:['Flat','Dome'],
  h:{paper:'The paper got wet, went soft and tore. Try a waterproof cover.',cloth:'Water dripped slowly through the cloth. Try a better cover.',straw:'The straw handle bent in the wind. Choose a stronger handle.',flat:'Spike stayed dry, but water collected on the flat cover. A dome shape lets water run off.',ok:'Spike is dry!'},
  home:'Make small umbrellas from paper, a plastic bag and cloth to protect a toy from rain; pour water on top with a cup.'},
 rampa:{t:'Ball Down the Ramp',why:'The higher the ramp, the faster the ball rolls and the farther it goes. Slippery surfaces slow the ball a little; a rough carpet slows it a lot. When we change only one thing at a time, we can see why.',d:'Change the height and surface to reach the basket.',intro:'We will let the ball roll down the ramp. Choose the height and the surface so the ball stops in the basket.',
  g:{h:'Height',s:'Surface'},hs:['1 box','2 boxes','3 boxes'],ss:['Carpet','Wood','Ice'],round:n=>`Round ${n}`,
  h:{short:'The ball stopped before the basket. Make the ramp higher or choose a slippery surface.',long:'The ball rolled past the basket. Make the ramp lower or choose a rougher surface.',ok:'The ball is right in the basket!'},
  home:'Use a book or a tray as a ramp. Put 1, 2, then 3 books under it, let a toy car go, and mark where it stops with tape.'},
 kaldirac:{t:'Lift It with a Lever',why:'A lever lets us lift heavy things with little force. The closer the pivot is to the load, the easier it is to push down on the other end.',d:'Move the pivot and lift the stone.',intro:'Zıpzıp wants to lift a big stone. We will make a lever with a plank and a pivot.',
  q:['Move the pivot. Can you lift the stone?','This stone is heavier! Where should the pivot go?','The pivot cannot move. How many bunnies must push to lift the stone?'],
  fulcrum:'Pivot',push:'Push',bunnies:'Bunnies',
  h:{fail:'The stone did not lift. Move the pivot closer to the stone or use more force.',ok:'The stone is in the air!'},
  home:'Put a ruler across a pencil. Put an eraser on one end and press the other end with your finger. What changes when the pencil moves closer to the eraser?'},
 ayak:{t:'How Many Feet?',d:'Measure the log with feet and compare.',intro:'How long is this log? We have no ruler, but we have feet! Let us measure.',
  q:['Measure with Spike’s feet. How many feet long is the log?','Now measure with Zıpzıp’s big feet. How many feet?','Why did we get different numbers?','So that everyone gets the same answer, let us measure with blocks that are all the same size. How many blocks?'],
  place:'Add a foot',placeB:'Add a block',why2:['Our feet are different sizes','The log got smaller'],
  why:'Spike’s feet are small, so we counted more feet. Zıpzıp’s feet are big, so we counted fewer. To get the same answer, everyone uses the same unit; that is why we have rulers.',
  home:'Measure the table, the rug or the sofa with your steps, then with your child’s steps. Compare the results.'},
 terazi:{t:'Which Is Heavier?',d:'Compare on the scale; is bigger always heavier?',intro:'We will put two things on the scale. The heavier side goes down. Guess first!',
  q:['Which one is heavier?','Which one is heavier?','Which one is heavier?','Which is the heaviest?'],
  items:{karpuz:'Watermelon',uzum:'Grapes','oyuncak-ayi':'Teddy bear',tas:'Stone',kitap:'Book',apple:'Apple'},
  why:'On a scale, the heavier side goes down. The teddy bear is bigger than the stone but lighter! Bigger is not always heavier; to find out, we weigh things.',
  home:'Hang two bags from a coat hanger to make a scale. Compare toys two at a time and line them up from lightest to heaviest.'},
 grafik:{t:'Pıtı’s Graph',d:'Count weather records and make a bar graph.',intro:'Pıtı watched the weather for ten days. Let us count how many days of each weather there were and make a graph.',
  q:['Make each bar the right height.','Which weather happened most?','Were there more rainy days or more cloudy days?'],own:'My diary graph',
  why:'A graph lets us see what we counted at a glance. The tallest bar shows the weather that happened most often.',
  home:'For a week, count who ate which fruit at breakfast; make a bar graph on paper with sticky notes.'},
 simetri:{t:'The Butterfly’s Other Wing',d:'Colour it like a mirror: symmetry.',intro:'One wing of the butterfly is coloured. Colour the other wing so it looks just like a mirror!',
  q:['Colour the other wing like a mirror.'],round:n=>`Butterfly ${n}`,
  why:'In symmetry, both sides of a line are the same, like a mirror. Butterflies, leaves and our faces are almost symmetrical.',
  home:'Fold a sheet of paper in half, drip paint on one half and close it. When you open it, you get a symmetrical butterfly!'},
 pizza:{t:'Share the Pizza',d:'Equal slices: half, quarter, third.',intro:'Some friends are going to eat pizza. Everyone must get a fair share. How many slices should we cut?',
  q:['There are two friends. How many slices should you cut so everyone gets the same?','There are four friends. How many slices?','There are three friends. How many slices?'],cut:'Slices',share:'Share',
  frac:['a half (1/2)','a quarter (1/4)','a third (1/3)'],each:f=>`Each friend got ${f} of the pizza.`,unfair:'The shares were not equal! A slice was left over or someone got less.',
  why:'When we cut a whole into equal parts, each part has a name: two parts make halves, four parts make quarters, three parts make thirds.',
  home:'Share a loaf, an apple or a paper pizza equally among the family. Give each part its name.'},
 carpma:{t:'Baskets of Carrots',d:'Multiplication with a repeat block.',intro:'Do you remember the repeat block from Code? We will use it to put carrots into baskets!',
  q:['Put 4 carrots in each of 3 baskets. How many carrots altogether?','Put 5 carrots in each of 2 baskets. How many altogether?','If we put 12 carrots in groups of 4, how many baskets do we need?'],
  baskets:'Baskets (repeat)',per:'In each basket',run:'Run',total:'How many carrots altogether?',howMany:'How many baskets?',
  why:'Adding the same number again and again is multiplication: 4 + 4 + 4 = 3 times 4 = 12. The repeat block also does the same job again and again.',
  home:'Use an egg box or cups to make groups like “2 buttons in each of 3 cups”; count first, then find the shortcut.'},
 kapi:{t:'The Door That Opens by Itself',d:'Sensor + if: smart gadgets.',intro:'How does a shop door open by itself? With a sensor and an if rule! You make the rule.',
  sc:['Shop door','Night light','Smart plant pot'],if:'IF',then:'THEN',sens:['someone comes near','it gets dark','the soil is dry','there is a sound'],acts:['open the door','turn on the light','water the plant','play music'],
  q:['Make the rule for the shop door.','Make the rule for the night light.','Make the rule for the smart plant pot.'],
  h:{bad:'This rule does not fit this gadget. Change the sensor or the job.',ok:'The rule works!'},
  why:'Sensors notice changes around them: movement, light, wetness, sound. The program says: if this happens, do that. Automatic doors, night lights and smart plant pots work this way.',
  home:'Look for gadgets with sensors: automatic doors, lights that switch on when you move, taps… Make an “if… then…” sentence for each one.'},
 robot:{t:'Design a Robot Arm',d:'Choose a gripper and joints, complete the jobs.',intro:'We will design a robot arm. For each job, choose the right gripper and enough joints.',
  g:{grip:'Gripper',joint:'Joints'},grip:['Claw','Magnet','Scoop'],joint:['1','2','3'],
  q:['Pick up the ball on the table.','Collect the scattered paper clips.','Carry the sand to the bucket.','Get the teddy bear from the high shelf.'],
  h:{grip:'This gripper does not suit this job. Try another gripper.',reach:'The arm could not reach. Add more joints.',ok:'The robot arm did the job!'},
  why:'Engineers design a robot for the job it will do. A claw grips, a magnet collects metal pieces, a scoop carries sand and water. Joints let the arm reach and bend.',
  dough:'Make it with play dough',doughText:'Make a jointed arm from play dough, straws and lolly sticks. Dough balls are the joints; add two sticks at the end as a claw.',
  home:'Make a robot arm from play dough, straws and lolly sticks. Which end is best for picking up pompoms?'},
 desen:{t:'Symmetry Pattern Studio',d:'Kaleidoscope drawing with mirror lines.',intro:'Every line you draw here repeats in the mirrors. Choose how many mirrors and start drawing!',
  mirrors:'Mirrors',clear:'Clear',size:'Brush',q:['Choose the mirrors and draw.'],
  why:'Shapes on both sides of a mirror line are the same. We see these patterns in rugs, tiles and snowflakes.',
  home:'Fold a sheet of paper into four and cut the corners; when you open it, you get a symmetrical snowflake.'},
 guvenlik:{t:'Who Can I Talk to on a Screen?',d:'Pıtı’s digital safety story.',intro:'Listen to Pıtı’s tablet adventure. In some places, you will help Pıtı.',
  pages:['Pıtı was playing her favourite game on the tablet.','Suddenly a message arrived: “Hello! What is your name, and where do you live?” Pıtı did not know this person.','Her mum read the message: “Thank you for showing me. We do not give our name, address or photo to people we do not know.”','Then a shiny button popped up in the game: “Click now for free gold!”','Pıtı had been playing for a long time. Her eyes were tired and her head began to ache.','Pıtı put the rules on a card: Do not share information with strangers. Ask a grown-up if you are not sure. Take screen breaks. Be kind online too.'],
  choice:{1:['I will write my address.','I will not write; I will show a grown-up.'],3:['I will click right away.','I will ask a grown-up first.'],4:['I will play for another hour.','I will turn off the tablet and play outside.']},
  good:'That is a very good choice!',bad:'Hmm, that is not safe. Let us think again.',why:'Screens have rules, just like real life. We do not share information with strangers, we ask a grown-up when we are not sure, and we take screen breaks.',
  home:'Make a family “screen rules” card together and keep it next to the tablet.'}
 },
 teacher:{title:'Teacher Panel',prog:'Progress across STEAM areas',acts:'activities',kaz:'Learning goal mapping',kazNote:'Numbers refer to the cognitive development goals of the Turkish Ministry of Education Preschool Programme (2013). Teachers are advised to check the mapping against the 2024 Türkiye Century Maarif Model.',
  kazNames:{2:'Makes predictions',4:'Counts objects',5:'Observes',6:'Matches by features',7:'Groups',8:'Compares features',9:'Orders',11:'Measures',12:'Recognises geometric shapes',13:'Recognises symbols',14:'Creates patterns',15:'Understands part–whole',16:'Simple addition/subtraction',17:'Cause and effect',18:'Explains time concepts',19:'Suggests solutions to problems',20:'Makes an object graph'},
  col:['Activity','Area','Goals','Status'],done:'Done',notyet:'—',
  pre:'Pre-test / post-test (pilot)',preNote:'This short form screens the child’s interest in STEAM with picture faces. It has not been validated; it is for pilot use only. Data stays on this device only; use a code instead of a name.',
  code:'Child code',phase:'Phase',phases:['Pre-test','Post-test'],begin:'Start the form',answers:['No','A little','Yes'],finish:'Saved.',
  items:['I like trying new things.','I wonder how things work.','Doing experiments is fun.','When something does not work, I try again.','I like counting and measuring.','I like building things.','I like watching living things in nature.','I like making pictures and patterns.','When I grow up, I could be a scientist or an engineer.','I ask about things I wonder about.'],
  records:'Records',none:'No records yet.',copy:'Copy as CSV',copied:'Copied.',copyFail:'Could not copy; select the text and copy it.',total:'Total',
  design:'Suggested pilot design',designText:'One group, pre-test–post-test: (1) Pre-test, (2) 4 weeks of 3 STEAM Lab activities per week plus the matching unplugged activity, (3) Post-test. With a small sample, pre and post scores can be compared with the Wilcoxon signed-rank test; activity usage records can be reported as implementation fidelity.',
  usage:'Usage log',reset:'Delete all data',resetq:'Are you sure? Tap again.',resetok:'Deleted.',del:'Delete'},
 story:{title:'From Stories to Experiments',sub:'Experiment cards to try after NOVA ECE Kids stories.',open:'Open activity',home:'Try at home'}
}};
/* Masal → etkinlik eşlemesi (masal no, TR başlık, EN başlık, etkinlik) */
const STORY_LINKS=[
 ['004','Bir Sana, Bir Bana','One for You, One for Me','pizza'],['010','Köpüklü Eller','Bubbly Hands','emme'],['011','Oyuncaklar Evine Dönüyor','The Toys Go Home','terazi'],
 ['012','Tekir’in Su Kabı','Tabby’s Water Bowl','buz'],['013','Yapraklar Neden Düşer?','Why Do Leaves Fall?','hava'],['014','Karıncaların Kış Hazırlığı','The Ants Get Ready for Winter','carpma'],
 ['017','Çök, Kapan, Tutun!','Drop, Cover, Hold On!','kule'],['020','Kule Yıkılınca','When the Tower Fell','kule'],['021','Beş Minik Civciv','Five Little Chicks','carpma'],
 ['023','Sokakta Şekil Avı','Shape Hunt in the Street','desen'],['024','Islak mı, Kuru mu?','Wet or Dry?','emme'],['026','Vrak’ın Kocaman Sesi','Vrak’s Big Voice','ses'],
 ['034','Kardan Adamın Kar Topları','The Snowman’s Snowballs','terazi'],['036','Kumbaramdaki Kuş','The Bird in My Money Box','terazi'],['037','Buz Nereye Gitti?','Where Did the Ice Go?','buz'],
 ['041','Ninemin Sazı','Granny’s Saz','ses'],['042','Ay Neden Değişiyor?','Why Does the Moon Change?','golge'],['043','Tabağımdaki Gökkuşağı','A Rainbow on My Plate','grafik'],
 ['044','Ekran Uykuya Dalınca','When the Screen Falls Asleep','guvenlik'],['045','Ela Önce Sorar','Ela Asks First','guvenlik'],['046','Tosbi’nin Kod Yolu','Tosbi’s Code Path','robot'],
 ['054','Kocaman Kutuyu Birlikte Taşıyalım','Let Us Carry the Big Box Together','kaldirac'],['061','Fil Gibi Ağır, Karınca Gibi Hafif','Heavy as an Elephant, Light as an Ant','terazi'],
 ['064','Yeşil Yandı, Yürüyoruz','The Light Is Green, Let Us Walk','kapi'],['065','Babamla Parkur Günü','Obstacle Course Day with Dad','rampa'],['066','Mırmır Büyük mü, Küçük mü?','Is Mırmır Big or Small?','terazi'],
 ['068','Fil Ne Kadar Uzun?','How Long Is the Elephant?','ayak'],['069','Sınıfın En Sevdiği Meyve','The Class’s Favourite Fruit','grafik'],['071','Uğur Böceğinin Benek Oyunu','The Ladybird’s Spot Game','pizza'],
 ['072','Ninemin Örüntülü Kilimi','Granny’s Patterned Rug','desen'],['073','Elif’in Sabırlı Tohumu','Elif’s Patient Seed','fasulye'],['076','Damla Damla Musluk','Drip, Drip, the Tap','emme'],
 ['077','Arı Vızvız’ın Uzun Yolu','Buzz the Bee’s Long Journey','fasulye'],['078','Kurbağa Nasıl Büyür?','How Does a Frog Grow?','fasulye'],['079','Fidan Dikme Günü','Tree Planting Day','fasulye'],
 ['080','Yağmur Yağınca Kim Çıkar?','Who Comes Out in the Rain?','hava'],['081','Batar mı, Yüzer mi?','Sink or Float?','batar'],['082','Beş Duyu Pazarı','The Five Senses Market','ses'],
 ['083','Gölge Oyunu Gecesi','Shadow Play Night','golge'],['084','Suyun Üstündeki Renkler','Colours on the Water','batar'],['085','Sarı ile Mavi Buluşunca','When Yellow Meets Blue','desen'],
 ['086','Pıtı Gökkuşağını Arıyor','Pıtı Looks for the Rainbow','hava'],['088','Taştaki Hayvanlar','Animals on Stones','simetri'],['089','Tıkır: Kapaklardan Bir Robot','Tıkır: A Robot Made of Lids','robot'],
 ['091','Meydandaki Heykel','The Statue in the Square','simetri'],['092','Kilden Kaplumbağa','A Clay Tortoise','robot'],['093','Şap Şap Güm!','Clap Clap Boom!','ses'],
 ['094','Kalın Ses, İnce Ses','Low Sound, High Sound','ses'],['095','Kaşık Kâse Orkestrası','The Spoon and Bowl Orchestra','ses'],['098','Kuşların Akşam Konseri','The Birds’ Evening Concert','ses'],
 ['100','Elif’in Rampası','Elif’s Ramp','rampa']];
